apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-route
spec:
  parentRefs:
    - name: mcp-gateway
      namespace: gateway-system
  hostnames:
    - 'mcp.127-0-0-1.sslip.io'
  rules:
    - name: mcp
      matches:
        - path:
            type: PathPrefix
            value: /mcp
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: '*'
              - name: Access-Control-Allow-Methods
                value: 'GET, POST, PUT, DELETE, OPTIONS, HEAD'
              - name: Access-Control-Allow-Headers
                value: 'Content-Type, Authorization, Accept, Origin, X-Requested-With'
              - name: Access-Control-Max-Age
                value: '3600'
              - name: Access-Control-Allow-Credentials
                value: 'true'
      backendRefs:
        - name: mcp-gateway
          port: 8080
    - name: tokens
      matches:
        - path:
            type: PathPrefix
            value: /tokens
      backendRefs:
        - name: mcp-gateway
          port: 8080
    - name: well-known
      matches:
        - path:
            type: PathPrefix
            value: /.well-known/oauth-protected-resource
      backendRefs:
        - name: mcp-gateway
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mcp-gateway
          port: 8080
