apiVersion: mcp.kuadrant.io/v1
kind: MCPServerRegistration
metadata:
  name: github
  namespace: mcp-test
spec:
  prefix: github_
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: github-mcp-external
  credentialRef:
    name: github-token
    key: token
  tokenURLElicitation:
    url: "{{ EXTERNAL_URL }}/tokens"
